// scripts/demo-schema.mjs
//
// Plain English: demo mode keeps its made-up data in its own small database
// inside a Durable Object (worker/src/demo/store.ts). That database needs the
// same tables as the real one, so this script copies every migration in
// worker/migrations into worker/src/demo/schema.gen.ts, in order, with one
// fingerprint (SHA-256) of them all. When a deploy adds a migration, the demo
// store sees the fingerprint change and rebuilds itself.
//
//   npm run demo-schema               write the file
//   npm run demo-schema -- --check    exit 1 if the file is out of date (the
//                                     deploy and the tests run this)
//
// Line endings are made LF first, so a Windows checkout (CRLF) and CI (LF)
// give the same file and the same fingerprint.

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
export const MIGRATIONS_DIR = join(ROOT, "worker", "migrations");
export const OUT_FILE = join(ROOT, "worker", "src", "demo", "schema.gen.ts");

/** Every *.sql in `dir`, in name order, with LF line endings. */
export function readMigrations(dir = MIGRATIONS_DIR) {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((name) => ({ name, sql: readFileSync(join(dir, name), "utf8").replace(/\r\n?/g, "\n") }));
}

/** One fingerprint over every migration's name and text, in order. */
export function schemaHash(list) {
  const h = createHash("sha256");
  for (const m of list) h.update(`${m.name}\n${m.sql}\n\0`);
  return h.digest("hex");
}

/** The generated module's text. */
export function schemaModule(list) {
  const lines = [
    "// schema.gen.ts",
    "//",
    "// GENERATED by scripts/demo-schema.mjs from worker/migrations. Do not edit:",
    "// run `npm run demo-schema` after adding a migration (the deploy and the tests",
    "// check it). Demo mode's store builds its tables from these (demo mode spec §3",
    "// ruling 11) and rebuilds itself when DEMO_SCHEMA_HASH changes.",
    "",
    "export const DEMO_SCHEMA: { name: string; sql: string }[] = [",
    ...list.map((m) => `  { name: ${JSON.stringify(m.name)}, sql: ${JSON.stringify(m.sql)} },`),
    "];",
    "",
    `export const DEMO_SCHEMA_HASH = "${schemaHash(list)}";`,
    "",
  ];
  return lines.join("\n");
}

function main(argv) {
  const arg = (name) => {
    const i = argv.indexOf(name);
    return i === -1 ? undefined : argv[i + 1];
  };
  const dir = resolve(arg("--migrations") ?? MIGRATIONS_DIR);
  const out = resolve(arg("--out") ?? OUT_FILE);
  const want = schemaModule(readMigrations(dir));
  if (argv.includes("--check")) {
    const have = existsSync(out) ? readFileSync(out, "utf8").replace(/\r\n?/g, "\n") : null;
    if (have !== want) {
      console.error(`demo-schema: ${out} is out of date with ${dir}. Run: npm run demo-schema`);
      return 1;
    }
    console.log("demo-schema: up to date.");
    return 0;
  }
  writeFileSync(out, want);
  console.log(`demo-schema: wrote ${out}.`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)));
