// demo-schema: the database schema bundled into the Worker for demo mode's
// store (demo mode spec §3 ruling 11). The script reads every migration and
// writes worker/src/demo/schema.gen.ts; --check says whether that file is out
// of date. Run here against a scratch folder, never the real migrations.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { schemaModule, schemaHash, readMigrations } from "../demo-schema.mjs";

const script = fileURLToPath(new URL("../demo-schema.mjs", import.meta.url));

function scratch() {
  const dir = mkdtempSync(join(tmpdir(), "demo-schema-"));
  const migrations = join(dir, "migrations");
  mkdirSync(migrations);
  writeFileSync(join(migrations, "0002_b.sql"), "CREATE TABLE b (x INTEGER);\r\n");
  writeFileSync(join(migrations, "0001_a.sql"), "-- a\nCREATE TABLE a (y TEXT);\n");
  writeFileSync(join(migrations, "notes.txt"), "not a migration");
  return { dir, migrations, out: join(dir, "schema.gen.ts") };
}

const run = (args) => spawnSync(process.execPath, [script, ...args], { encoding: "utf8" });

test("writes every migration in name order with its SHA-256", () => {
  const s = scratch();
  try {
    const r = run(["--migrations", s.migrations, "--out", s.out]);
    assert.equal(r.status, 0, r.stdout + r.stderr);
    const text = readFileSync(s.out, "utf8");
    assert.match(text, /GENERATED by scripts\/demo-schema\.mjs/);
    // In name order, line endings as LF (a Windows checkout's CRLF must not change the hash), .sql only.
    const list = readMigrations(s.migrations);
    assert.deepEqual(list.map((m) => m.name), ["0001_a.sql", "0002_b.sql"]);
    assert.equal(list[1].sql, "CREATE TABLE b (x INTEGER);\n");
    assert.ok(text.indexOf("0001_a.sql") < text.indexOf("0002_b.sql"));
    assert.ok(!text.includes("notes.txt"));
    assert.ok(!text.includes("\r"));
    // The hash covers each file's name and text, in order.
    const h = createHash("sha256");
    for (const m of list) h.update(`${m.name}\n${m.sql}\n\0`);
    assert.equal(schemaHash(list), h.digest("hex"));
    assert.match(text, new RegExp(`DEMO_SCHEMA_HASH = "${schemaHash(list)}"`));
    assert.equal(text, schemaModule(list));
  } finally {
    rmSync(s.dir, { recursive: true, force: true });
  }
});

test("--check exits 1 after a migration is added and 0 after regenerating", () => {
  const s = scratch();
  try {
    assert.equal(run(["--migrations", s.migrations, "--out", s.out]).status, 0);
    let c = run(["--check", "--migrations", s.migrations, "--out", s.out]);
    assert.equal(c.status, 0, c.stdout + c.stderr);
    writeFileSync(join(s.migrations, "0003_c.sql"), "CREATE TABLE c (z TEXT);\n");
    c = run(["--check", "--migrations", s.migrations, "--out", s.out]);
    assert.equal(c.status, 1);
    assert.match(c.stderr, /npm run demo-schema/);
    assert.equal(run(["--migrations", s.migrations, "--out", s.out]).status, 0);
    assert.equal(run(["--check", "--migrations", s.migrations, "--out", s.out]).status, 0);
  } finally {
    rmSync(s.dir, { recursive: true, force: true });
  }
});

test("--check exits 1 when the generated file is missing", () => {
  const s = scratch();
  try {
    const c = run(["--check", "--migrations", s.migrations, "--out", s.out]);
    assert.equal(c.status, 1);
  } finally {
    rmSync(s.dir, { recursive: true, force: true });
  }
});

test("the real generated file is up to date", () => {
  const c = run(["--check"]);
  assert.equal(c.status, 0, c.stdout + c.stderr);
});
